vich_uploader:
    db_driver: orm

    mappings:
        users:
           uri_prefix: /upload/users
           upload_destination: '%kernel.project_dir%/public/upload/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: true
